### ISSUE TITLE
确定采访地点和形式

### ISSUE THREAD

**Issue by songbaoqiang** [hushanzhenyi/startup#9]
1:罗老师希望借鉴13邀多种采访地点的方式。 景涛需要反馈思路，如果可行，出方案。

- [x] 需要和巨浪沟通
- [x] 需要我们确定主题后筹备

**Comment by lijingtaotao** [comment]
好的我先想想@ @songbaoqiang

**Comment by songbaoqiang** [comment]
> 好的我先想想@ @songbaoqiang

@lijingtaotao 我也考虑一下。。。

**Comment by songbaoqiang** [comment]
@hexixueshe  认为：每个场景气息不太一样，讲述的内容也可以有所侧重——和空间目前的运营方向相关。
1、81号院——数字资产研究院。我就不多赘述了，各位是财经专家。罗老师是学术与技术委员会的成员之一。
2、和平宾馆，建国以后第一家涉外酒店，老楼为建筑大师杨廷宝先生设计的现代主义作品，已是文保单位，目前仍用作客房使用。为了满足市场需求，罗老师1984年在旁边另起了一栋新楼，整个设计理念很值得讲述。目前罗老师带着酒店新老管理人员，制定后疫情时代的运营策略。（场景中有那桐府邸花园留下的假山）
3、429共享院——白塔寺老街改造项目之一。据我所知，法国大使馆还参与了投资，可以在采访中讲述空间与人的关系，尤其是“共享”理念。
